name: app_name
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3
  file_picker: ^5.3.4
  url_launcher: ^6.1.12
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^2.3.2
  package_info_plus: ^4.1.0
  flutter_dotenv: ^5.1.0
  dots_indicator: ^3.0.0
  #form validation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  #DIO
  dio: ^5.3.2
  awesome_dio_interceptor: ^1.0.0
  shimmer: ^3.0.0
  #riverpod:
  flutter_riverpod: ^2.3.9
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  path_provider: ^2.1.0
  flutter_lints: ^2.0.2
  freezed: ^2.4.2

  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - lib/.env.uat
    - lib/.env.staging
    - lib/.env.production


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Century
      fonts:
        - asset: assets/fonts/CenturyGothic.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#e1f5fe"
  color_dark: "#042a49"
  image: assets/images/mana_logo.png
  image_dark: assets/images/mana_logo.png
  icon_background_color: "#ffffff"
  android_12:
    color: "#42a5f5"
    icon_background_color: "#eeeeee"
    image: assets/images/mana_logo.png
  fullscreen: false
  web: true